### ISSUE TITLE
Elasticsearch production cluster "403: cannot get endpoints" errors

### ISSUE THREAD

**Issue by jaytaylor** [kubernetes/examples#111]
Following the docs for creating a [production cluster](https://github.com/kubernetes/examples/tree/master/staging/elasticsearch/production_cluster), I get the following 403 endpoints errors from the master, client, and data pod logs:

```
[2017-10-16 20:59:07,180][WARN ][io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider] [Annihilus] Exception caught during discovery javax.ws.rs.WebApplicationException : HTTP 403 User "system:serviceaccount:default:elasticsearch" cannot get endpoints in the namespace "default".
javax.ws.rs.WebApplicationException: HTTP 403 User "system:serviceaccount:default:elasticsearch" cannot get endpoints in the namespace "default".
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:25)
	at io.fabric8.kubernetes.api.ExceptionResponseMapper.fromResponse(ExceptionResponseMapper.java:16)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.checkResponse(ClientProxyImpl.java:302)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.handleResponse(ClientProxyImpl.java:725)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.doChainedInvocation(ClientProxyImpl.java:683)
	at org.apache.cxf.jaxrs.client.ClientProxyImpl.invoke(ClientProxyImpl.java:224)
	at com.sun.proxy.$Proxy29.endpointsForService(Unknown Source)
	at io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider.getNodesFromKubernetesSelector(K8sUnicastHostsProvider.java:123)
	at io.fabric8.elasticsearch.discovery.k8s.K8sUnicastHostsProvider.buildDynamicNodes(K8sUnicastHostsProvider.java:106)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:313)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:219)
	at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:146)
	at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:124)
	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:1007)
	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:361)
	at org.elasticsearch.discovery.zen.ZenDiscovery.access$6100(ZenDiscovery.java:86)
	at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1384)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This seems related to #105, but this cluster doesn't use [RBAC](https://kubernetes.io/docs/admin/authorization/rbac/). I decided to go ahead and try applying the [rbac.yaml](https://github.com/kubernetes/examples/blob/202271d18dc1387f516214d599c47155720f8ab7/staging/elasticsearch/rbac.yaml) anyways and now everything is working happily!

```
kubectl create -f staging/elasticsearch/rbac.yaml
```

```
[2017-10-16 21:04:27,542][INFO ][cluster.service          ] [X-Cutioner] detected_master [Magik][lL30c9mgShuRPZuJZXMB7Q][es-master-0blnl][inet[/10.244.1.195:9300]]{data=false, master=true}, added {[Magik][lL30c9mgShuRPZuJZXMB7Q][es-master-0blnl][inet[/10.244.1.195:9300]]{data=false, master=true},}, reason: zen-disco-receive(from master [[Magik][lL30c9mgShuRPZuJZXMB7Q][es-master-0blnl][inet[/10.244.1.195:9300]]{data=false, master=true}])
[2017-10-16 21:04:27,560][INFO ][cluster.service          ] [X-Cutioner] added {[Annihilus][7pHiQCwuSX6tD4t_TqG1Lg][es-client-6kxsj][inet[/10.244.1.196:9300]]{data=false, master=false},}, reason: zen-disco-receive(from master [[Magik][lL30c9mgShuRPZuJZXMB7Q][es-master-0blnl][inet[/10.244.1.195:9300]]{data=false, master=true}])
```

This leads me to suspect that the current production cluster example may be broken.

### Questions

1. Why does applying rbac.yaml fix the production cluster example when RBAC is not installed on the cluster?

2. Should the application of rbac.yaml be added to the production cluster example?

Thank you!
Jay

**Comment by jaytaylor** [comment]
Still would like to know the why's behind this.

**Comment by ahmetb** [comment]
@jaytaylor I recommend finding the owner of the example from here: https://github.com/kubernetes/kubernetes/commits/v1.7.0/examples/elasticsearch and asking them. I'm not sure they see this issue.

**Comment by jaytaylor** [comment]
Thanks @ahmetb, will do.
