### ISSUE TITLE
Selenium example

### ISSUE THREAD

**Issue by fleeto** [kubernetes/examples#114]
It seems that there is no geckodriver installed in the image `google/python-hello`, so the python code won't work as expected

Another image inodb/python-selenium can support the example.

**Comment by ludovicbonivert** [comment]
I get following error `>>> check_browser("CHROME")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in check_browser
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 151, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 240, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: None`

when running  check_browser("CHROME") or check_browser("FIREFOX"). Is this error related?
